In [1]:
import pandas as pd
from tqdm.notebook import tqdm

In [2]:
fishs = ['щука', 'судак', 'окунь', 'берш', 'речная форель', 'озерная форель', 'елец', 'чехонь', 'сом', 'голавль', 'язь',
         'карп', 'жерех', 'лещ', 'карась', 'линь', 'пескарь', 'ротан', 'плотва', 'красноперка', 'налим', 'густера',
         'амур', 'ерш', 'сазан', 'подуст', 'толстолобик', 'вобла', 'хариус']

In [3]:
dt = pd.read_csv('forecast1.csv', sep=';')
train_data = []
for idx, row in tqdm(dt.iterrows()):
    if row['щука'] > -1:
        data = dt[idx - 3: idx + 1]
        temps = list(data['day_temp'])
        press = list(data['day_pressure'])
        obls = list(data['day_obl'])
        phens = list(data['day_phen'])
        dirs = list(data['day_dir'])
        winds = list(data['day_wind'])
        areal = row['areal']
        month = row['month']
        day = row['day']
        for fish in fishs:
            row_ = {'areal': areal, 'month': month, 'day': day, 'fish': fish, 'forecast': row[fish]}
            for k in range(len(temps)):
                row_.update({
                    'temperature_{}'.format(k): temps[3 - k],
                    'pressure_{}'.format(k): press[3 - k],
                    'obl_{}'.format(k): obls[3 - k],
                    'phenomen_{}'.format(k): phens[3 - k],
                    'wind_direction_{}'.format(k): dirs[3 - k],
                    'winds_{}'.format(k): winds[3 - k],
                })
            train_data.append(row_)

HBox(children=(FloatProgress(value=1.0, bar_style='info', max=1.0), HTML(value='')))

In [4]:
train_dt = pd.DataFrame(train_data)

In [5]:
train_dt.describe()

,month,day,forecast,temperature_0,pressure_0,winds_0,temperature_1,pressure_1,winds_1,temperature_2,pressure_2,winds_2,temperature_3,pressure_3,winds_3
count,2523.00000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000
mean,6.62069,15.781609,0.420927,11.908046,743.862069,3.344828,11.080460,743.747126,3.045977,11.034483,743.574713,3.126437,10.954023,742.885057,2.988506
std,3.23210,8.733264,0.493806,13.139927,24.578557,2.186216,13.198939,24.525656,2.095336,12.960900,24.682879,2.083760,13.371776,25.084351,2.141937
min,1.00000,1.000000,0.000000,-26.000000,628.000000,0.000000,-28.000000,627.000000,0.000000,-28.000000,626.000000,0.000000,-26.000000,625.000000,0.000000
25%,4.00000,8.000000,0.000000,2.000000,743.000000,2.000000,2.000000,742.000000,2.000000,1.000000,742.000000,2.000000,1.000000,740.000000,2.000000
50%,6.00000,15.000000,0.000000,14.000000,749.000000,3.000000,12.000000,749.000000,3.000000,12.000000,748.000000,3.000000,10.000000,746.000000,2.000000
75%,9.00000,23.000000,1.000000,22.000000,755.000000,4.000000,22.000000,753.000000,4.000000,22.000000,755.000000,4.000000,22.000000,755.000000,4.000000
max,12.00000,31.000000,1.000000,32.000000,776.000000,11.000000,31.000000,781.000000,12.000000,31.000000,782.000000,11.000000,35.000000,779.000000,11.000000

In [6]:
min_ = {
    'temperature_0': -60, 'temperature_1': -60, 'temperature_2': -60, 'temperature_3': -60,
    'pressure_0': 500, 'pressure_1': 500, 'pressure_2': 500, 'pressure_3': 500,
    'winds_0': 0, 'winds_1': 0, 'winds_2': 0, 'winds_3': 0, 'day': 1
}

max_ = {
    'temperature_0': 50, 'temperature_1': 50, 'temperature_2': 50, 'temperature_3': 50,
    'pressure_0': 900, 'pressure_1': 900, 'pressure_2': 900, 'pressure_3': 900,
    'winds_0': 20, 'winds_1': 20, 'winds_2': 20, 'winds_3': 20, 'day': 31
}

In [7]:
for key in min_:
    train_dt[key] = (train_dt[key] - min_[key])/(max_[key] - min_[key])

In [8]:
train_dt.describe()

,month,day,forecast,temperature_0,pressure_0,winds_0,temperature_1,pressure_1,winds_1,temperature_2,pressure_2,winds_2,temperature_3,pressure_3,winds_3
count,2523.00000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000,2523.000000
mean,6.62069,0.492720,0.420927,0.653710,0.609655,0.167241,0.646186,0.609368,0.152299,0.645768,0.608937,0.156322,0.645037,0.607213,0.149425
std,3.23210,0.291109,0.493806,0.119454,0.061446,0.109311,0.119990,0.061314,0.104767,0.117826,0.061707,0.104188,0.121562,0.062711,0.107097
min,1.00000,0.000000,0.000000,0.309091,0.320000,0.000000,0.290909,0.317500,0.000000,0.290909,0.315000,0.000000,0.309091,0.312500,0.000000
25%,4.00000,0.233333,0.000000,0.563636,0.607500,0.100000,0.563636,0.605000,0.100000,0.554545,0.605000,0.100000,0.554545,0.600000,0.100000
50%,6.00000,0.466667,0.000000,0.672727,0.622500,0.150000,0.654545,0.622500,0.150000,0.654545,0.620000,0.150000,0.636364,0.615000,0.100000
75%,9.00000,0.733333,1.000000,0.745455,0.637500,0.200000,0.745455,0.632500,0.200000,0.745455,0.637500,0.200000,0.745455,0.637500,0.200000
max,12.00000,1.000000,1.000000,0.836364,0.690000,0.550000,0.827273,0.702500,0.600000,0.827273,0.705000,0.550000,0.863636,0.697500,0.550000

In [9]:
def one_hot(df, cols):
    """
    @param df pandas DataFrame
    @param cols a list of columns to encode 
    @return a DataFrame with one-hot encoding
    """
    for each in cols:
        dummies = pd.get_dummies(df[each], prefix=each, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(each,axis = 1)
    return df

oh_cols = ['month', 'fish', 'obl_0', 'obl_1', 'obl_2', 'obl_3', 'phenomen_0', 'phenomen_1', 'phenomen_2', 'phenomen_3',
          'wind_direction_0', 'wind_direction_1', 'wind_direction_2', 'wind_direction_3']
train_dt = one_hot(train_dt, oh_cols)

In [10]:
train_dt

,areal,day,forecast,temperature_0,pressure_0,winds_0,temperature_1,pressure_1,winds_1,temperature_2,...,wind_direction_2_ЮЗ,wind_direction_3_-,wind_direction_3_В,wind_direction_3_З,wind_direction_3_С,wind_direction_3_СВ,wind_direction_3_СЗ,wind_direction_3_Ю,wind_direction_3_ЮВ,wind_direction_3_ЮЗ
0,Алтайский край,0.700000,1.0,0.700000,0.6275,0.05,0.681818,0.6225,0.05,0.763636,...,0,1,0,0,0,0,0,0,0,0
1,Алтайский край,0.700000,0.0,0.700000,0.6275,0.05,0.681818,0.6225,0.05,0.763636,...,0,1,0,0,0,0,0,0,0,0
2,Алтайский край,0.700000,1.0,0.700000,0.6275,0.05,0.681818,0.6225,0.05,0.763636,...,0,1,0,0,0,0,0,0,0,0
3,Алтайский край,0.700000,0.0,0.700000,0.6275,0.05,0.681818,0.6225,0.05,0.763636,...,0,1,0,0,0,0,0,0,0,0
4,Алтайский край,0.700000,1.0,0.700000,0.6275,0.05,0.681818,0.6225,0.05,0.763636,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2518,Московская область,0.766667,1.0,0.763636,0.6200,0.15,0.736364,0.6100,0.05,0.754545,...,0,0,1,0,0,0,0,0,0,0
2519,Московская область,0.766667,1.0,0.763636,0.6200,0.15,0.736364,0.6100,0.05,0.754545,...,0,0,1,0,0,0,0,0,0,0
2520,Московская область,0.766667,1.0,0.763636,0.6200,0.15,0.736364,0.6100,0.05,0.754545,...,0,0,1,0,0,0,0,0,0,0
2521,Московская область,0.766667,1.0,0.763636,0.6200,0.15,0.736364,0.6100,0.05,0.754545,...,0,0,1,0,0,0,0,0,0,0
2522,Московская область,0.766667,1.0,0.763636,0.6200,0.15,0.736364,0.6100,0.05,0.754545,...,0,0,1,0,0,0,0,0,0,0

In [11]:
del train_dt['areal']

In [12]:
y = train_dt['forecast'].values.astype('int32')
del train_dt['forecast']
X = train_dt.values

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [15]:
model.fit(X_train, y_train)

C:\Users\Xiaomi\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
preds = model.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score

print(accuracy_score(preds, y_test))

0.8138613861386138

In [18]:
model.predict_proba(X_test)

array([[0.79817192, 0.20182808],
       [0.73798928, 0.26201072],
       [0.19957919, 0.80042081],
       ...,
       [0.6900819 , 0.3099181 ],
       [0.49020635, 0.50979365],
       [0.07782222, 0.92217778]])